### ISSUE TITLE
Image preview not updating after submit form

### ISSUE THREAD

**Issue by luismunyoz** [jasny/bootstrap#140]
Way to reproduce it:
1. Select a photo. The photo is showed.
2. Submit the form. The photo is uploaded ok
3. Reset the form. No photo is showed.
4. Select a photo. The photo is NOT showed
5. Submit the form. The photo is uploaded ok

I'm using AjaxFileUpload when I click submit button.

**Comment by jasny** [comment]
Can't reproduce
