### ISSUE TITLE
drop down sub menu doesn't work in mobile

### ISSUE THREAD

**Issue by mrjikey** [jasny/bootstrap#230]
drop down sub menu doesn't work in mobile & tablets ...but it works on desktop .. 
u can try click on the action and another action link at below
http://g2o.com.my/3rd/

**Comment by kashyapmukkamala** [comment]
Hey can you please provide the fix (or the link for it) for the offcanvas scroll issue? I have tried a lot of things but I could not get it to work.

**Comment by jasny** [comment]
@kashyapmukkamala This issue hasn't been closed. I haven't released in a while. To fix it add the following CSS:

```css
.navmenu-nav.dropdown-menu { position:relative; }
```

**Comment by kashyapmukkamala** [comment]
Is that the same fix for the left offcanvas scrolling too? 

If so, should I just add this to the existing css or replace the current 

CSS which is? 

.navmenu-nav.dropdown-menu{position:static;margin:0;padding-top:0;float:none;border:none;-webkit-box-shadow:none;box-shadow:none;border-radius:0}

**Comment by kashyapmukkamala** [comment]
I was looking more at this class

navmenu-fixed-left, .navmenu-fixed-right, .navbar-offcanvas {
position: fixed;
z-index: 1050;
top: 0;
bottom: 0;
overflow-y: auto;
border-radius: 0;
}

as thats the wrapper class for my menu

**Comment by jasny** [comment]
@kashyapmukkamala Please don't use this issue tracker as a forum. If you need help with development, please use [StackOverflow](http://www.stackoverflow.com].

This ticket is for an issue with the submenu not working on mobile defines. If that isn't the issue you're experiencing, you're posting in the wrong place.

Don't edit library files (general rule). The above CSS should be addedd to your own stylesheet.

**Comment by shaneparsons** [comment]
At a first glance, adding `.navmenu-nav.dropdown-menu { position:relative; }` seemed to have fixed the issue of the dropdown's links not working, however, It then brings up the issue of not being able to re-click the initial drop down to collapse it (or any other dropdown for that matter).

Any ideas?

**Comment by Asner** [comment]
Adding `.dropdown-backdrop{position: relative;}` seems to fix this issue (it fixed mine). Someone would like to test this?

**Comment by EncoreTeam** [comment]
Ok so the backdrop from bootstrap is covering the drop down menus just change the backdrop in the bootstrap css file:
 dropdown-backdrop{position: static;}

**Comment by shaneparsons** [comment]
@EncoreTeam - Thanks, works for me!

**Comment by dinglestein** [comment]
THANK YOU!

**Comment by razinbunsu** [comment]
Thanks a bunch!

**Comment by chaoxfu** [comment]
Thanks

**Comment by allaire** [comment]
thanks `.dropdown-backdrop{position: relative;}` works well

**Comment by fr-olivier** [comment]
@EncoreTeam Oh god thank you for finding out, it was driving me crazy.

**Comment by kosiakMD** [comment]
.dropdown-backdrop
div-class created by clear Boostrap
decisions:
1) change z-index
2) delete element each time

**Comment by Minstel** [comment]
That is solved in https://github.com/jasny/bootstrap/issues/462

**Comment by hirenmehta97** [comment]
.navmenu-nav.dropdown-menu, .dropdown-backdrop {position:relative!important;}
CSS worked for me.
