### ISSUE TITLE
Use better input mask

### ISSUE THREAD

**Issue by jasny** [jasny/bootstrap#249]
See http://robinherbots.github.io/jquery.inputmask/

**Comment by Misiu** [comment]
@jgladwill +1 on this implementation. It looks and feels better.

**Comment by gambala** [comment]
+1 or please fix this issue https://github.com/jasny/bootstrap/issues/337

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.
