### ISSUE TITLE
Issues when navmenu is fixed-right

### ISSUE THREAD

**Issue by human39** [jasny/bootstrap#253]
I'm currently using Jasny to implement a slide in right side menu bar to my app.  I'm seeing some weirdness with Firefox (29.0).

Please take a look at this fiddle:

http://jsfiddle.net/human39/tV3Mf/1/

When you click the toggle icon you'll see the first problem:  The menu just "appears" instead of sliding in.  However, if click the toggle again, the menu correctly slides away.

The other issue, you can use the same fiddle.

Resize the HTML view screen with the menu enabled.  You'll see the menu stay in its place.. instead of flowing with the browser window.

Both of these issues are FireFox only.  I've tested both on Chrome and IE and seem to do the right (expected) thing.  This seems to be not an issues when the navmenu is fixed-left.

Let me know if you need any more information.

**Comment by 640miles** [comment]
Had the same issue in FF.
Adding .navmenu-fixed-right {left: auto !important;} didn't solve the problem.
But adding body.canvas-sliding, body.canvas-slid {left: auto !important;} did. Not sure, probably there is a better solution, at least it helped to solve an issue for me.

**Comment by FlorianSteller** [comment]
Hi, is there any reason for setting inline style with fix size of left and right to the "navmenu-fixed-right" class?

**Comment by gazofnaz** [comment]
I have a site with both a left and right hand fixed menu.

The fix from @rustyhutchison worked for one side, but it broke the other. I had to dig into the javascript to fix it completely. See my comments in the offcanvas.js below.

```
    OffCanvas.prototype.slide = function (elements, offset, callback) {
        // Use jQuery animation if CSS transitions aren't supported
        if (!$.support.transition) {
            var anim = {}
            anim[this.placement] = "+=" + offset
            return elements.animate(anim, 350, callback)
        }

        var placement = this.placement

        // gazofnaz edit: No longer used. See below
        // var opposite = this.opposite(placement)

        elements.each(function() {
            if ($(this).css(placement) !== 'auto')
                $(this).css(placement, (parseInt($(this).css(placement), 10) || 0) + offset)

            // gazofnaz edit: this broke the slide in animation
            // if ($(this).css(opposite) !== 'auto')
            //     $(this).css(opposite, (parseInt($(this).css(opposite), 10) || 0) - offset)
        })

        this.$element
            .one($.support.transition.end, callback)
            .emulateTransitionEnd(350)
    }
```

Removing `$(this).css(opposite, (parseInt($(this).css(opposite), 10) || 0) - offset)` seemed to address the issue for me. But I'm not clear on the knock on effects. YMMV
