### ISSUE TITLE
Long text strings get overflow

### ISSUE THREAD

**Issue by proudbyte** [jasny/bootstrap#263]
Hi,

I've experienced a small issue with your plugin.
If provided a huge file name then it will overflow thus breaking the whole design.
Perhaps you might correct this issue, for now i'm using max-width but it's far from being a good solution... do you think you could fix it so it could be used with col-...-.. class giving it a good integration with bootstrap forms?

http://s8.postimg.org/je8pgmdnp/Screen_Shot_2014_06_26_at_15_49_30.png

thank you

**Comment by eduardojmatos** [comment]
Tks @rivalex :grinning:

**Comment by gparajon** [comment]
Awesome!!! Thanks @rivalex

**Comment by jasny** [comment]
@rivalex Thanks for the fix. You're making a lot of people happy.

If you are able to send in a pull request it would be super duper awesome.

**Comment by BernieCook** [comment]
Worked a treat for me. Thanks @rivalex

**Comment by Minstel** [comment]
Already done, closing.

**Comment by kranthikadechur-k** [comment]
.custom-file-label{white-space: nowrap;overflow: hidden;text-overflow: ellipsis;padding-right:80px}

**Comment by kingslee-p** [comment]
> .custom-file-label{white-space: nowrap;overflow: hidden;text-overflow: ellipsis;padding-right:80px}

worked was using react strap Thanks @kranthikadechur-k

**Comment by Sajeyks** [comment]
> Hi Jansy, I don't know if you have just fix long text but i want to share my solution. This is a simple css solution but work fast, responsive and fine
> 
> ```css
> .fileinput-filename {
>     display: inline-block;
>     overflow: hidden;
>     vertical-align: middle;
>     /* new lines */
>     width: 100%;
>     position: absolute;
>     left: 0;
>     padding-left: 30px;
>     white-space: nowrap;
>     text-overflow: ellipsis;
> }
> ```
> 
> in attached the result test, hope this will be useful thanks Alex ![demo](https://cloud.githubusercontent.com/assets/580591/5146407/79df5f3e-71ac-11e4-9692-c3268941a398.png)
Thanks for that.. After all those years and it still saved me now 😄 ..

**Comment by Sajeyks** [comment]
> Hi Jansy, I don't know if you have just fix long text but i want to share my solution. This is a simple css solution but work fast, responsive and fine
> 
> ```css
> .fileinput-filename {
>     display: inline-block;
>     overflow: hidden;
>     vertical-align: middle;
>     /* new lines */
>     width: 100%;
>     position: absolute;
>     left: 0;
>     padding-left: 30px;
>     white-space: nowrap;
>     text-overflow: ellipsis;
> }
> ```
> 
> in attached the result test, hope this will be useful thanks Alex ![demo](https://cloud.githubusercontent.com/assets/580591/5146407/79df5f3e-71ac-11e4-9692-c3268941a398.png)

2014 and it still works. Thanks for the save man! 👍
