### ISSUE TITLE
Offcanvas menu doesn't scroll on chrome on android when sub menu is expanded

### ISSUE THREAD

**Issue by Timonium** [jasny/bootstrap#275]
Site tested http://jasny.github.io/bootstrap/examples/navmenu-push/
Tested on Nexus 7, Galaxy Tab3, S4, Moto X and LG Opitmus X4

Scrolling is fine when no subs are expanded but is disabled when they are opened.

**Comment by fkranenburg** [comment]
Same problem here, I'm on a Sony Xperia Z3 (Chrome browser).

**Comment by iemand002** [comment]
android 4.3, chrome and chrome beta, only problems in landscape...

**Comment by Minstel** [comment]
This was solved together with https://github.com/jasny/bootstrap/issues/462 in PR https://github.com/jasny/bootstrap/pull/502
