### ISSUE TITLE
Bootstrap version 3.2.0 vs Bootstrap 3.1.0 conflict

### ISSUE THREAD

**Issue by djmy** [jasny/bootstrap#278]
When i updated to the latest bootstrap version 3.2.0 the off canvas nav on mobile breaks  completely. How can I achieve this to work for Bootstrap 3.2.0? It works great on 3.1.0 but not on 3.2.0? Any advise would help thank you!

![desktop-1](https://cloud.githubusercontent.com/assets/8239931/3666481/26fee2a4-11f2-11e4-9c49-2ebffdf79918.gif)

![mobile-1](https://cloud.githubusercontent.com/assets/8239931/3666482/2bed5d0e-11f2-11e4-98e6-a4504032f726.gif)

**Comment by Minstel** [comment]
`translate3D` was reverted in bootstrap, so I guess we can close this.
