### ISSUE TITLE
Problems with disableScrolling: Offcanvas Navbar doesn't work as should be on mobile.

### ISSUE THREAD

**Issue by ManuelRiveraC** [jasny/bootstrap#284]
I have problems using the plugin "Off canvas Menu" in mobile. Apparently "disableScrolling: true" doesn't work. Everything moves, including menu navigation and the full content. The funny thing is that it works as it should be resizing my web browser on desktop.

I recorded a short video to better understand the problem: https://www.screenr.com/AvXN

By the way, I'm using the offical demo example from http://jasny.github.io/bootstrap/examples/navbar-offcanvas/, so you can see that I'm not doing anything wrong.

**Comment by Minstel** [comment]
Looks like this was fixed. Closing.
