### ISSUE TITLE
Offcanvas menu (positioned on right) works incorrect in IE9

### ISSUE THREAD

**Issue by paulradzkov** [jasny/bootstrap#289]
In IE9 when offcanvas menu expanded there is no negative `left` inline styles on `.canvas` element. See gif-animation attached: in Chrome behavior is correct, in IE9 (emulated from IE11) there is no `left` style. 
IE10 and IE11 works fine. IE8 not tested.

![offcanvas-ie9](https://cloud.githubusercontent.com/assets/475929/3908884/de3b89e2-2307-11e4-9531-41ddfd033c8c.gif)

**Comment by Minstel** [comment]
I can see that problem for `reveal` type of menu. Other menu types work ok.
