### ISSUE TITLE
Fixed-position toggle button and window resize

### ISSUE THREAD

**Issue by djmtype** [jasny/bootstrap#294]
I wanted the nav's toggle button set at a fixed position so it's always in view, rather than the entire nav. 
Therefore, I declare: 

```
.navbar-toggle {
    position: fixed;
    top: 0;
    left: 0;
}
```

Problem occurs when resizing my window. When I toggle the menu open and leave it open, then resize my browser, the `navbar-toggle` button is now positioned 300px from the left and the toggle class `canvas-slid` remain attached even though the menu is closed. 

Here is the generated code: 

```
<button type="button" class="navbar-toggle canvas-slid" data-toggle="offcanvas" data-target=".navbar-offcanvas" data-canvas="body" style="left: 300px;">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
```

[Watch the video](https://cloudup.com/i4ebyF79RfG)

Is there a way to set a window resize listener (if that's the issue)?

**Comment by Minstel** [comment]
@djmtype I understand that too much time passed) But if it's still actual - can you please update video example, as link is not working anymore.

**Comment by djmtype** [comment]
@Minstel Sorry, I must have erased the video when I cleaned house. I believe I had found another method for adding a Bootstrap off-canvas menu because each time the user would scroll open/close the menu, scroll some more, open the menu – the menu toggle would eventually become unreachable, hidden above, outside the viewport. 

And now with Bootstrap 4 and using flexbox, there's probably a better way.
