### ISSUE TITLE
Suggested: fluid height for columns

### ISSUE THREAD

**Issue by xermus** [jasny/bootstrap#308]
I suggest that you add support for "same height columns" which work also when changing the screen dimension. So when 3 lg columns are visible, it should use the max height of the row's highest column to adjust the two remaining columns to the max height. And at the same time the whole thing should be responsive, meaning that when the viewport changes to sm-2, that the row is updated accordingly.

This is a missing feature in Bootstrap, and it would be just AWESOME if you could make this work. I have tried several plugins, they all fail and/or do not work well with Bootstrap.

**Comment by jasny** [comment]
Should be solved with flexbox. Not going to implement.
