### ISSUE TITLE
Close menu after clikc on one pager

### ISSUE THREAD

**Issue by Turqueso** [jasny/bootstrap#315]
I'm using it one a one-page. Is there a way to make the menu toogle after users selects and menu scrolls to the section?

**Comment by Turqueso** [comment]
any help?

**Comment by Turqueso** [comment]
Currently i'm testing this:

```
$(function() {
			$('#navbar a').on('click', function(){
					if($('.navbar-toggle').css('display') !='none'){
							$(".navbar-toggle").trigger( "click" );
					}
			});
	});
```

So far is working fine

**Comment by invalidusernam3** [comment]
You can use` $(".navmenu").offcanvas('hide');` on the click event, where the selector is your off canvas menu

**Comment by Minstel** [comment]
Closing, because @BrettGregson gave correct answer, and there is no feedback. Also it's not an issue, just a question on *how to*.
