### ISSUE TITLE
button padding

### ISSUE THREAD

**Issue by simonsheridan** [jasny/bootstrap#323]
the following lines break bootstrap button sizing classes.  Is there a reason it's there?

```
.btn-labeled {
  padding-top: 0;
  padding-bottom: 0;
}
```

I'm going to submit a pull request with this styling removed

**Comment by jasny** [comment]
I'm unsure that this is still required. Please test what happends if this is removed.

**Comment by Minstel** [comment]
@simonsheridan I do not see that something wrong happens, when applying bootstrap button sizing classes. Can you provide a http://jsfiddle.net example?
