### ISSUE TITLE
can not open any link in dropdown

### ISSUE THREAD

**Issue by Q8HMA** [jasny/bootstrap#328]
Hello

I have problem in http://jasny.github.io/bootstrap/examples/navmenu/
it not work fine in ios safari and chrome
any link in dropdown can not open and when i click it ,it close navmenu

but any other link not in dropdown it open fine

thnx

really i need help on it

**Comment by Q8HMA** [comment]
any help ??

**Comment by iemand002** [comment]
Removing the ```navmenu-nav``` class makes the link working but then the sub items style is like an "pop-up"
```
<ul class="dropdown-menu navmenu-nav">

to

<ul class="dropdown-menu">
```
Also scrolling is not working on mobile... 
(Android, Chrome)

**Comment by iemand002** [comment]
ow, the answer is over here: #230

**Comment by Minstel** [comment]
Solved in https://github.com/jasny/bootstrap/issues/462
