### ISSUE TITLE
File upload - Set max file size

### ISSUE THREAD

**Issue by MadEddieFFS** [jasny/bootstrap#334]
Am I missing a way of setting the maximum file size for the file upload widget ? If not, I guess this would be a feature request...

Thanks

**Comment by jasny** [comment]
No you can check this yourself using `.on('change.bs.fileinput')`. I'll add it as feature request.

**Comment by MadEddieFFS** [comment]
superb - thanks for quick reply

**Comment by ilsonlasmar** [comment]
I would like to clear the input file if the file size exceeds 8 mb but returns me an error "Uncaught TypeError: is not the function undefined" when I call the method this.fileinput ('clear').

      validate_size = (e) ->   
        if this.files.length > 0
          f = this.files[0]
          if (f.size > 8388608 || f.fileSize > 8388608)
            alert("Arquivo maior que permitido. (Max. 8 MB)") 
            this.fileinput('clear') //error here

      $("#document_" + size).fileinput()
      $("#document_" + size).on('change.bs.fileinput', validate_size)

could help me?

thanks

**Comment by DarkmoonLabs** [comment]
Have you had a chance to implement this?  
Barring that, could you give a complete example of how to accomplish this with the current release?

**Comment by jasny** [comment]
No, unfortunately I have 0 time. It should be rather simple though: http://www.html5rocks.com/en/tutorials/file/dndfiles/

**Comment by rock-walker** [comment]
really, I cannot retrieve "files" property from event argument in
"change.bs.fileinput".
