### ISSUE TITLE
how to hide offcanvas on menu click?

### ISSUE THREAD

**Issue by dcsan** [jasny/bootstrap#335]
currenlty when i click the offcanvas menu items, the menu will stay up on screen (covering the content) while the new page loads.

how do i get the menu to hide?

I tried trapping the click and hiding it myself but now it takes two clicks to open - because I guess an internal variable doesn't know the correct state.

Is there an internal API to call and close the menu?

```
Template.sidemenu.events
  'click #navItems': (evt) ->
    console.log("click offCanvas")
    $('.navmenu').fadeOut()
```

I see this method but not sure how to call it:
```
  OffCanvas.prototype.toggle = function () {
    if (this.state === 'slide-in' || this.state === 'slide-out') return
    this[this.state === 'slid' ? 'hide' : 'show']()
  }

```

not sure where/if an instance of this class is created?

**Comment by jasny** [comment]
Please read the docs. It's discussed here: http://jasny.github.io/bootstrap/javascript/#js-programmatic-api

**Comment by ahwolf** [comment]
I tried a lot of the different options, the way I managed to fix this issue was adding a 
```{display:none}```
 to the css.

**Comment by ccdiego5** [comment]
how to you fix it **ahwolf**? where you puck the {display:none}?

**Comment by ccdiego5** [comment]
i soldved this way

`    $(".navbar .navmenu-nav a").click(function(){
    $('selector').offcanvas('hide');
    });`
