### ISSUE TITLE
jasny bootstrap inputmask is using the same namespace as jquery.inputmask

### ISSUE THREAD

**Issue by RobinHerbots** [jasny/bootstrap#337]
This leads to conflicts when using both.  Can you rename the inputmask plugin in jasny bootstrap?

**Comment by gambala** [comment]
Same problem, after 9 months and nothing happened with issue

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version.

**Comment by vercotux** [comment]
Same issue here.

@gambala's workaround does not work unfortunately. Getting a ```TypeError: jQuery(...).inputmask is not a function``` issue if I invoke `noConflict()`.

@jasny Any estimate when the next major version is coming out?

**Comment by jasny** [comment]
Before the end of the year. The new version will be for BS4 though.

In v3, please use the `.noConflict()` method.
