### ISSUE TITLE
Check for valid image extension while upload

### ISSUE THREAD

**Issue by mpkumar87** [jasny/bootstrap#339]
Hi,

I am using jasny bootstrap file uploader for uploading images. Need to specify allowed extension for images. If not valid type then alert to show 'Not valid file'.  Please guide me to fix this problem.

Thanks,
Premkumar M.

**Comment by alexiskattan** [comment]
+1

**Comment by jasny** [comment]
You should use the [`accept`](http://www.w3schools.com/tags/att_input_accept.asp) attribute.
