### ISSUE TITLE
File input event never triggered

### ISSUE THREAD

**Issue by michaeldjeffrey** [jasny/bootstrap#343]
There is no way to catch a change event on a file input in an environment where they may be added or removed.

http://plnkr.co/edit/20o4uf2KB3O5mjGDzSu2?p=preview

**Comment by jasny** [comment]
You're simply not copying the events. `form.append($(".fileinput").clone());` should be `form.append($(".fileinput").clone(true));`. See the jQuery docs: http://api.jquery.com/clone/

**Comment by michaeldjeffrey** [comment]
I've updated the plunker to have a move apt example. 
It goes against the principle of least surprise that a changing file input wouldn't throw a change event on itself regardless of when or how it was added to the page.

http://plnkr.co/edit/20o4uf2KB3O5mjGDzSu2?p=preview

**Comment by jasny** [comment]
"jasny event" is outputted, but not any of the other events. Yes, noticed that before. Triggering a namespaced event will only work when [you listen on the exact namespace](http://stackoverflow.com/questions/4718841/namespaced-custom-events-trigger). I consider this a jQuery issue.

Try the trigger button here: http://plnkr.co/edit/8H2tv2kOT7CozHdzNwWI?p=preview

Anyway, this is [the](https://github.com/twbs/bootstrap/blob/master/js/affix.js#L105) [way](https://github.com/twbs/bootstrap/blob/master/js/carousel.js#L127) [that](https://github.com/twbs/bootstrap/blob/master/js/modal.js#L28) Bootstrap does it, which has the same behaviour.

**Comment by michaeldjeffrey** [comment]
I would accept that as an issue with jquery if the demo wasn't using jquery 1.4. If you use anything but the oldest version available, it works as expected.

The bootstrap examples are fine because those elements don't normally throw events. 
They don't catch an event happening on that element, stop it from moving forward, then continue to rethrow it somewhere else.

**Comment by tiliv** [comment]
In my opinion, the confusion here is that the event being re-triggered is not coming from the input.  It subverts expectations.
