### ISSUE TITLE
Input file validation using Jasny v3.1.3 and jQuery Validator v1.13.1

### ISSUE THREAD

**Issue by femosso** [jasny/bootstrap#345]
I was trying to validate an input file (from Jasny v3.1.3) with the jQuery Validator v1.13.1 but when the file is loaded, the validation is not done.

In order to make it simple, I created an example in fiddle with the file input validation using only jQuery Validator: http://jsfiddle.net/n73es6qc/
And another fiddle with Jasny + Bootstrap + jQuery Validator: http://jsfiddle.net/Luf0ks9b/3/

Please check that in the first fiddle, when I upload some file different from video/mp4 and click in some place on the page, the error message is display for the input file. However, the same doesn't seem to work on the second fiddle (which uses Jasny). In this case the validation is NOT done promptly. It is done, though, when I click in submit button, but that is not the behavior I'm trying to reach.

I already took a look at this question: http://stackoverflow.com/questions/22387874/jquery-validate-plugin-bootstrap-jasny-bootstrap-file-input-regex-validation. In the fiddle example of it, something similar to what I want to have is done. When some wrong file format is uploaded, the error is promptly displayed. But, in this answer, they used Jasny v2.3.0. a different version from what I'm using.

**Comment by poratuk** [comment]
Do not saw any problem here.
