### ISSUE TITLE
Failed to initialize Off Canvas through JavaScript.

### ISSUE THREAD

**Issue by dontripi** [jasny/bootstrap#347]
Hello, i try to create an offcanvas menu via javascript please if you can give me some example to can set it up, my code is this:

$(document).ready(function(){
            $('.navmenu').offcanvas({autohide:true, toggle:true, placement:'left'});
                        $("#nuevo").click(function (){  
                     $(".navmenu").offcanvas('toggle');
                 });
});

i don't know how to set up my html to make it works with offcanvas i want to toggle only when click nuevo, please if you can give me an example i will be very thankful with you.

Thank's.

**Comment by jasny** [comment]
Can you please create a jsfiddle demonstrating the problem.

**Comment by Minstel** [comment]
No feedback, closing.
