### ISSUE TITLE
Alert fixed top on page with side menu

### ISSUE THREAD

**Issue by iemand002** [jasny/bootstrap#351]
The `alert-fixed-top` is not showing right.
http://jsfiddle.net/wp64873x/

The css should be something like this:

```
@media(min-width:992px){
    .alert-fixed-top{
        left: 330px;
        right: 30px;
        width: auto;
        margin: 0;
    }
}
```

http://jsfiddle.net/y05n7a67/

**Comment by poratuk** [comment]
This will be actual only for not offcanvas menu. 
If this are apply to all sites, this will be wrong.
