### ISSUE TITLE
Offcanvas menu not working properly

### ISSUE THREAD

**Issue by ericntd** [jasny/bootstrap#355]
Recently, when the offcanvas menu is toggled, there is a weird white space showing on top of it
![screen shot 2015-03-24 at 2 33 05 pm](https://cloud.githubusercontent.com/assets/510825/6796847/e9fa6ed8-d234-11e4-8b3a-51c0519ff71f.png)

**Comment by ericntd** [comment]
Plus the animation is sliding down which is wrong (it feels like the default bootstrap animation instead of jasny)

**Comment by jasny** [comment]
Thanks for reporting this

**Comment by Minstel** [comment]
That happens when bootstrap 3.2.0 styles are used, that is currently the case on given site. On later version tested (3.3.5) everything is ok.
