### ISSUE TITLE
3.1.3+

### ISSUE THREAD

**Issue by ksnyde** [jasny/bootstrap#360]
I see a number of worthy additions to components like offcanvas that are only in master, not a tagged release. What is your thinking on this? It would be nice if a stabilized/tagged version could be made that incorporates some of the changes over the past 8 months.

**Comment by jasny** [comment]
True, it's a matter of time (or the lack of) I'm afraid. Testing and releasing hasn't been automated, so it's takes quite a bit of effort.

Most of the changes are pull requests, so I'm a little reluctant to release them without rigorous testing.

**Comment by ksnyde** [comment]
Yes I can certainly understand the fight we all have with time. Maybe a semver tag with explicit mentioning of being a beta might lower the expectation? It could also help share the testing responsibilities with  the community rather than you having to shoulder it all. 

Either way, what you've done is great. I hope to have an Ember addon which wraps your off-canvas menu available soonish. If you're interested I'll send you the link once its ready.

Here's to the `v3.1.4-beta-1` release :)

**Comment by hotzenklotz** [comment]
I would love to see a new release as well. It has been 64 commits and a few months since the last one. Any ETA?

**Comment by jasny** [comment]
It's been on hold for a bit, but I've just started putting some effort in it. Note that this project is looking for collaborators. If anyone is interested, please let me know.

**Comment by hotzenklotz** [comment]
That's good to hear. I would love to see a 3.1.4-beta if necessary. It makes no sense to merge PR after PR and not release them. After all "patch"-upgrades should only fix bugs anyway.

**Comment by jasny** [comment]
3.2.0-beta is available. Working on gettng a team of collaborators to take this project further (see #430)

**Comment by hotzenklotz** [comment]
Thank you. I really appreciate it.

**Comment by hotzenklotz** [comment]
@jasny As far as I can tell the update is not yet available on NPM. Do you mind pushing it there?

**Comment by jasny** [comment]
@hotzenklotz I currently don't have ownership of jasny-bootstrap on NPM. I've requested Escaleno to make me the owner and cc-ed npm support.

**Comment by hotzenklotz** [comment]
Thank you very much. You are the man!
