### ISSUE TITLE
Difference between 'reveal' and 'push'

### ISSUE THREAD

**Issue by ksnyde** [jasny/bootstrap#361]
I've sat there looking at the demos of the 'reveal' and 'push' effects but I can't distinguish any difference between them. Am I missing something?

**Comment by jasny** [comment]
* With push, the menu is stuck to the left (or right) side of the canvas. The canvas and the menu move.
* With reveal the menu is sitting behind the canvas. When the canvas moves it reveals the menu. The menu never moves.
