### ISSUE TITLE
Side push menu Navbar colour change on large screens

### ISSUE THREAD

**Issue by eMagineTech** [jasny/bootstrap#365]
The offcanvas push menu in your example has a colored navbar for xs and sm screen sizes. But the color becomes white for medium and large screens. See the attached pics for clarity.
Please keep the color same on all screens

Also, is it possible to put the contents of side menu on main navigation bar for large screen sizes as with standard bootstrap navigation?

The side menu works great on mobiles and tablets. Thank you for your hard work.

![jash-left-push-large](https://cloud.githubusercontent.com/assets/12121037/7336761/0719b496-ec2b-11e4-9b29-67aec917b921.PNG)
![jash-left-push-small](https://cloud.githubusercontent.com/assets/12121037/7336760/06743bd8-ec2b-11e4-8f3c-6b2f7f5bdded.PNG)

**Comment by jasny** [comment]
The demo is only a demo. Create however you like it to look and work.

For md, lg and xl screens, it isn't a matter of color, but the whole bar isn't shown, just the button. If you want to show a show bar, there isn't much reason to use offcanvas for these sizes.

I any case. Not an issue. Please do **not** respond on this comment.
