### ISSUE TITLE
Target is undefined on row whitout link (rowlink)

### ISSUE THREAD

**Issue by phlegx** [jasny/bootstrap#366]
Hi!

If some row don't have a link (eg. no edit permission for this entry in row) I get a Javascript error on line 35:

``` javascript
TypeError: target is undefined
if (target.click) {
```

Here we need to add a check, if the variable `target` is defined. 

**BUGFIX**

Please change line 35 from:

``` javascript
if ($(e.target)[0] === target) return
```

to

``` javascript
if (typeof target == 'undefined' || $(e.target)[0] === target) return
```

**Comment by raoel** [comment]
Same here, I didn't use an actual link on my table but a ui-sref (from ui-router -> http://angular-ui.github.io/ui-router/site/#/api/ui.router ).

**Comment by tonkajuris** [comment]
Thanks for the included script for the fix.  I ran into this today.
