### ISSUE TITLE
Support exif orientation

### ISSUE THREAD

**Issue by cameronhymas** [jasny/bootstrap#370]
I'm not sure if I'm missing something simple, but I can't seem to get images that are taller than they are wide to keep their orientation when visible in the preview.  Is there a setting to required it to maintain orientation, or is there some css I haven't figured out?  If not then maybe this is a feature request.

**Comment by jasny** [comment]
The images you're testing with are probably on their side, but have a [exif orientation](http://sylvana.net/jpegcrop/exif_orientation.html). Most image applications will automatically rotate the image, but the fileinput plugin doesn't read the exif meta data at all.

Note that your server side code will probably also not read the exif (unless you programmed it to) when handling the image.

**Comment by neo22s** [comment]
Hello, that would be cool to do, we do it int he server side but if could be done in the browser...much better! ;) thanks

**Comment by telcy** [comment]
This is a good sample file http://cloudmining-review.com/wp-content/uploads/0217748_rotated.jpg
Looks fine in the browser and desktop image preview. But is wrong rotated when you see it in jasny bootstrap preview.

**Comment by basteln3rk** [comment]
EXIF orientation is difficult to do correctly, remember there are 8 cases. Discussion [here](http://stackoverflow.com/questions/20600800/js-client-side-exif-orientation-rotate-and-mirror-jpeg-images/20600801#20600801]. If required, use a library like [JavaScript-Load-Image](https://github.com/blueimp/JavaScript-Load-Image)

**Comment by jasny** [comment]
I have an implementation for this, but it requires [exif-js](https://github.com/exif-js/exif-js). Maybe I can make it optional somehow.

**Comment by rizalibnu** [comment]
how to impelentation exif-js in jasny file input?

**Comment by congkevin** [comment]
@jasny 
I also have the same problem.
" fileinput plugin doesn't read the exif meta data at all."
Regarding that, can you tell how to enable jasny fileinput plugin to read exif data?

Best regards,

**Comment by jasny** [comment]
You need to include exif.js. Than you can do:

```js
+function() {
    var rotate_classes = {
        1: '',
        2: 'fileinput-flip-horizontal',
        3: 'fileinput-rotate-full',
        4: 'fileinput-flip-vertical',
        5: 'fileinput-rotate-right fileinput-flip-horizontal',
        6: 'fileinput-rotate-right',
        7: 'fileinput-rotate-left fileinput-flip-horizontal',
        8: 'fileinput-rotate-left'
    };

    $('.fileupload').on('change', function(e, result) {
        if (!result || result === 'clear') return;
        
        var bin_string = window.atob(result.replace(/^data:.+;base64,/, ''));
        var bin_file   = new EXIF.BinaryFile(bin_string);
        var info  = EXIF.findEXIFinJPEG(bin_file);

        if(typeof info.Orientation != "undefined" && typeof rotate_classes[info.Orientation] != "undefined" && rotate_classes[info.Orientation]) {
            $(this).find('.fileupload-preview img').addClass(rotate_classes[info.Orientation]); 
        }
    });
}();
```

**Comment by oculairmedia** [comment]
Hi Jasny i'm working on a project where your file input method is being used.
I followed your instructions above but it didn't work.
shoudl this : fileupload-preview
be this ? : fileinput-input
any help would be fantastic!

**Comment by Minstel** [comment]
Already implemented.
