### ISSUE TITLE
Offcanvas with canvas body option set not opening after hide.

### ISSUE THREAD

**Issue by mcfarljw** [jasny/bootstrap#371]
I've tried it with the following example using the console:

http://jasny.github.io/bootstrap/examples/navmenu-push/

If you open the console and run the following commands:

```
$('.navmenu').offcanvas({canvas: 'body'}) //opens properly with push
$('.navmenu').offcanvas('hide') //closes properly with push
$('.navmenu').offcanvas({canvas: 'body'}) //won't open a second time
```

Is there something I'm doing wrong programmatically when closing offcanvas that is preventing it from opening a second time. *This isn't a problem when using data tags directly in the html on programmatically using jquery.*

**Comment by jasny** [comment]
You're initializing the offcanvas twice. It opens the first time because option `toggle` (Toggles the off canvas element on invocation) defaults to `true`. The second initialization has no effect.

```js
$('.navmenu').offcanvas({canvas: 'body', toggle: false}) //initialize
$('.navmenu').offcanvas('show') //opens properly with push
$('.navmenu').offcanvas('hide') //closes properly with push
$('.navmenu').offcanvas('show') //opens properly with push
```

**Comment by brybam** [comment]
How would we switch the canvas target a second time after the first initialization? For example if we wanted to load it one way, but then possibly switch it to false without running the initialization again?
