### ISSUE TITLE
Off Canvas menu scrolls with canvas

### ISSUE THREAD

**Issue by ausgates** [jasny/bootstrap#372]
Off Canvas menu scrolls with canvas, additionally there isn't a way to close the menu.

**Comment by jasny** [comment]
You can close the menu through JavaScript

    $('#menu').offcanvas('hide');

**Comment by Donny1** [comment]
Hi there, 

i've got the same issue, when opening the menu on mobile. In Google Chrome there does not seem to be a problem. The nav-toggle always stays on top. However, when opening in Safari the navbar-toggle just stays on top of the page, it doesnt seem to be fixed. Also the menu scrolls with the page slightly and I'm also able to scroll to the side (including the menu) ( see screenshots )

![img_4961 copy](https://cloud.githubusercontent.com/assets/11333251/7914771/648e2e1c-0879-11e5-94d5-9730212823d0.jpg)
![img_4959 copy](https://cloud.githubusercontent.com/assets/11333251/7914772/6706caaa-0879-11e5-9e78-b10ac48698ce.jpg)

Any fix for this?

**Comment by jasny** [comment]
There is an `overflow: hidden` on the body, which should disable all scrolling. It looks like safari isn't respecting that.

**Comment by Donny1** [comment]
Well, 

as mentioned in issue 331 switching the navmenu-fixed-left class to the navmenu-fixed-right class fixes everything. Just tested this. However I want my menu on the left, not right. So gonna start comparing the classes now and see where things go wrong.

Arjen.

**Comment by Donny1** [comment]
Well, after an hour i havent figured it out yet, my jquery knowledge just is not enough. I do think you have to look in this direction: http://stackoverflow.com/questions/12434416/overflowhidden-on-body-is-broken-in-ios6/28673415#28673415

Would love to know if you are able to fix this issue. 

Also: great work on this plugin, tnx for making this!

**Comment by poratuk** [comment]
This problem are same as in the #388. Its will be fixed in PR #521
