### ISSUE TITLE
Bower installing jasny-bootstrap 3.1.3 still has mixins file imported

### ISSUE THREAD

**Issue by yangshun** [jasny/bootstrap#373]
I ran `bower install jasny-bootstrap` and `scss/jasny-bootstrap.scss` is as follows:
```
// Twitter Bootstrap's "variables.scss" should already be imported

// Core variables and mixins
@import "variables";
@import "mixins";

// Core CSS
@import "grid-container-smooth";
@import "button-labels";

// Components
@import "nav-tab-alignment";
@import "navmenu";
@import "alerts-fixed";

// Components w/ JavaScript
@import "offcanvas";
@import "rowlink";
@import "fileinput";
```

The `mixins` file is attempted to be imported but there is no such file, which causes my `grunt-sass` task to fail.

Does anyone know the reason?

**Comment by jasny** [comment]
Yes, it's a know as solved bug. The fix just hasn't been released yet. Please install and build from the master branch.
