### ISSUE TITLE
Multiple issues with offcanvas menu.

### ISSUE THREAD

**Issue by benzon** [jasny/bootstrap#378]
1) Links in dropdowns dont work on smartphones, work in browser tho but that dos not help.

2) When you scroll the menu and if you keep scrolling when you hit the bottom, content and offcanvas menu will get out of "shape" looks awfull!

3) On Smartphone when pushing the site the menu dos not close, this is annoying if a user decides he dos not want to go to a new page.

4) The JavaScript toggles dos not work optimal, if you call the show function it will not push the content to the site, but it will hide under the top menu, but if you push the normal button first, and then call the show function it shows correct, the issue with it not working, is we cant add support for Swipe gestures.

**Comment by benzon** [comment]
Hope you are looking in to all this, looks like some of the issues has bin posted quite some time now by others.

But i guess i got to finde a nother alternative, since it seems to buggy currently sadly, i love the idea behind Jasny Bootstrap.

**Comment by jasny** [comment]
@benzon Could you please post this as 4 individual issues. Thanks

**Comment by benzon** [comment]
Just added all 4 of them :)

**Comment by jasny** [comment]
Thanks :smile:
