### ISSUE TITLE
Using JS show an offcanvas menu, disregards the data properties

### ISSUE THREAD

**Issue by benzon** [jasny/bootstrap#382]
The JavaScript toggles dos not work optimal, if you call the show function it will not push the content to the site, but it will hide under the top menu, but if you push the normal button first, and then call the show function it shows correct, the issue with it not working, is we cant add support for Swipe gestures.

**Comment by jasny** [comment]
As a workaround, please use JavaScript to initialize the offcanvas element rather than using data attributes.

**Comment by dstN** [comment]
for me it's the other way round. initializing with js stops the push-effect.

**Comment by Minstel** [comment]
@benzon Not quite clear what is happening. Can you create an example in [jsfiddle](https://jsfiddle.net/)?

**Comment by Minstel** [comment]
@benzon I do not see any problem when opening menu with JS functions, they work correctly. For swipe support there is issue https://github.com/jasny/bootstrap/issues/154
Closing this, as there is no feedback.
