### ISSUE TITLE
data-disable-scrolling="true" not working on iPhone

### ISSUE THREAD

**Issue by ricardoruwer** [jasny/bootstrap#388]
Hi.
I was using the option data-disable-scrolling="true" but the overflow:hidden on body aren't working on iPhones, so I did that to work correctly:

CSS:
.lock {height:100%;overflow:hidden;width:100%;position:fixed;}

JS:
Changed .css("overflow", "hidden") to .addClass("lock")
Added .removeClass("lock") after the .removeData("offcanvas-style")

And it worked perfectly for me.
It also fixed a bug with the address bar that was doing some visual bugs when scrolling to bottom of the page on menu.

Sorry for my bad english :-)

**Comment by ricardoruwer** [comment]
Another fix:

Change the CSS to:
.lock {height:100%;overflow:hidden;width:100%;position:fixed;-webkit-overflow-scrolling: touch;}

The -webkit-overflow-scrolling: touch; will fix another visual bug that happens only at iPhones...

**Comment by IdanAdar** [comment]
I tested the push menu in an iPhone device and scrolling is still possible despite applying the above suggestions.

I am using v3.1.3.

**Comment by poratuk** [comment]
https://github.com/jasny/bootstrap/pull/521
