### ISSUE TITLE
3.1.3 Release doesn't remove reference to mixins.scss and thus fails to compile.

### ISSUE THREAD

**Issue by christianmagill** [jasny/bootstrap#395]
The 3.1.3 release which removed the mixins.less reference fails to remove the mixins reference in jasny-bootstrap.scss

https://github.com/jasny/bootstrap/releases/tag/v3.1.3

This causes the compile to fail when importing via Bower.

Perhaps a 3.1.4 release should be made that includes the correction that has since been made.

**Comment by ardoramor** [comment]
Any update on 3.1.4 release? As mentioned, 3.1.3 SASS build is currently broken because of this.

**Comment by steefaan** [comment]
+1

**Comment by alexcrawford** [comment]
Such a simple thing to tag a new release, can we get this done please?

**Comment by baggsie** [comment]
Any progress with this please?

**Comment by jasny** [comment]
I'm not satisfied with the current state of the project, so I'm not releasing a new stable version.

I will have release beta versions with community fixes: [v3.2.0-beta.1](https://github.com/jasny/bootstrap/releases/tag/v3.2.0-beta.1)

**Comment by matgargano** [comment]
Is this a joke?

**Comment by cariboufute** [comment]
Have converted the mixins.less file into the missing _missing.scss file, which fixes the bug for the moment. Made a pull request for it.

**Comment by Minstel** [comment]
@jasny Is this solved and should be closed?
