### ISSUE TITLE
Offcanvas closes when you select date from bootstrap date picker

### ISSUE THREAD

**Issue by vallurisundeep** [jasny/bootstrap#396]
Hi,

I have used bootstrap date picker  in my project and when I select date offcanvas menu is geeting closed. How to prevent this issue?

**Comment by spectrus** [comment]
Do you have an reproducible example?

**Comment by vallurisundeep** [comment]
here is the URL to see the issue,

vallurisundeep.in/safeMeds/generate-qr.html 

Please click om hamburger icon and then select date. Canvas is closing. appreciate your help.

THanks
Sundeep

**Comment by jasny** [comment]
@spectrus Can you create a [JSFiddle ](https://jsfiddle.net/jasny/k9K5d/) demonstrating this issue?

**Comment by spectrus** [comment]
Were you talking to @vallurisundeep ?

**Comment by jasny** [comment]
Yes, sorry...

**Comment by Minstel** [comment]
I tested opening reveal menu with datepicker and found no such problem. As the is no feedback on issue, let's consider it closed for now.
