### ISSUE TITLE
Auto positioning doesn't work correct in Safari (iOS)

### ISSUE THREAD

**Issue by rinader** [jasny/bootstrap#400]
Reveal menu appears, while Pulling down page in Safari (iOS, macos). 

(It works ok in chrome.)

**Comment by LastRose** [comment]
I had a problem like this, for me it was on window size. In any case, in offcanvas.js there are some defaults OffCanvas.DEFAULTS - set the placement option from auto to where you want your menu (top, bottom, left, right). Not sure if there is a better way of setting this.

**Comment by jasny** [comment]
Indeed auto placement isn't that accurate. Best is to set it explicitly with the `position` option.
