### ISSUE TITLE
Not able to scroll after toggling navigation once.

### ISSUE THREAD

**Issue by ghost** [jasny/bootstrap#403]
The scroll bar disappears and it stops scrolling after toggling the navigation once. Check the code in the given link.

http://bonline.in/btree/

**Comment by LastRose** [comment]
in the offcanvas.js file, there is a default called "disableScolling" set to true, change that to false and it should solve your problem. Not sure if there is a better way of doing this.

**Comment by Minstel** [comment]
@ghost Provided link is not working.

**Comment by Minstel** [comment]
Closing, as there is no feedback.
