### ISSUE TITLE
Bower - different files

### ISSUE THREAD

**Issue by pinin** [jasny/bootstrap#404]
Bower install contains different files.
offcanvas not modal option

**Comment by jasny** [comment]
I don't understand the issue.

**Comment by jasny** [comment]
No response from OP

**Comment by marhalpert** [comment]
@jasny Same here mate. 
I have done `bower cache clean` deleted the bower_components folder.
and then done `bower install` again.

It installs a version of off canvas that does nor have the modal option.

**Comment by marhalpert** [comment]
Fixed by adding this as the `"jasny-bootstrap": "^3.2.0-beta.1"` in the bower.json

**Comment by marhalpert** [comment]
Actually `"jasny-bootstrap": "^3.2.0-beta.1"` is not working at all try  `"jasny-bootstrap": "git@github.com:jasny/bootstrap.git#9ab27cddf27fb9b3ad2ce44ea87717722a1585f3"` has manu bugs fixed and improvements
