### ISSUE TITLE
Closes canvas automatically

### ISSUE THREAD

**Issue by pbijvani** [jasny/bootstrap#406]
Hello,

I am using jasny bootstrap for sliding menu. Its working find on desktop and mobile browser. We recently developed an mobile app using ionic/phonegap/cordova where I am loading my web page in iframe, which works fine on android. but on ios, when i click on button it slides the menu, but then closes automatically. I tried a lot but couldnt get it fixed.

Can anyone help?

thanks

**Comment by jva91** [comment]
Look at this issue #230 maybe this will fix your problem

**Comment by kosiakMD** [comment]
.dropdown-backdrop
div-class created by clear Boostrap
decisions:
1) change z-index
2) delete element each time

**Comment by Minstel** [comment]
@pbijvani Is this still actual? If so, please provide example in http://jsfiddle.net

**Comment by Minstel** [comment]
Closing as there is no response. Also, if @kosiakMD correctly spotted the reason, it's already fixed.
