### ISSUE TITLE
Menu does not autohide on iOS

### ISSUE THREAD

**Issue by wouterij** [jasny/bootstrap#415]
On iOS 9.1 when tapping outside of the menu, the menu does not automatically hide. 

I've found that replacing the following line in offcanvas.js 

`$(document).on('click', $.proxy(this.autohide, this))`

with 

`$(document).on('click touchstart', $.proxy(this.autohide, this))`

seems to fix the issue. Can you confirm this? I hope this helps someone else.

**Comment by jasny** [comment]
@wouterij It would be great if you could send in a pull request for this. Thanks!

**Comment by KBog** [comment]
This fixed the autohide issue on iOS. Thanks!

**Comment by jasny** [comment]
Merged PR

**Comment by phoxoey** [comment]
Bower install still has the old code FYI
