### ISSUE TITLE
Auto positioning isn't working in demo

### ISSUE THREAD

**Issue by rahulkadukar** [jasny/bootstrap#417]
This link is to show the navbar and then using offcanvas to reveal or hide the menu, but it is not working as expected.

http://www.jasny.net/bootstrap/examples/navbar-offcanvas/

**Comment by jasny** [comment]
This is caused by auto positioning causing the navmenu to come from the top instead of the right.

As a workaround we can use `position` option.

**Comment by muhammad-ihsan** [comment]
hi @jasny , how to fix it? mine too, the offcanvas it coming from top

**Comment by jasny** [comment]
@muhammad-ihsan Explicitly set where the offcanvas should come from with the `position` option.

**Comment by poratuk** [comment]
You are can change (from example):
` <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navbar-offcanvas" data-canvas="body">`
Just add `data-placement="right" `

` <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-placement="right" data-target=".navbar-offcanvas" data-canvas="body">`
