### ISSUE TITLE
data-disableScrolling not taked into account for Offcanvas

### ISSUE THREAD

**Issue by simchaba** [jasny/bootstrap#418]
data-disableScrolling is not taked into account for Offcanvas as it is lowercased by data, 
the test for the lower case value isn't right your code is on line 1OO
```javascript
if (this.options.disablescrolling) {
        this.options.disableScrolling = this.options.disablescrolling
        delete this.options.disablescrolling
    }
```

and it should be :
```javascript
if (typeof this.options.disablescrolling != "undefined") {
        this.options.disableScrolling = this.options.disablescrolling
        delete this.options.disablescrolling
    }
```

Hope it can help.

**Comment by jasny** [comment]
There is no casing in HTML attributes. disableScrolling is converted to `data-disabled-scrolling`. This is part of the HTML5 spec.

See http://stackoverflow.com/a/20985285/1160754
