### ISSUE TITLE
.offcanvas() function is undefined

### ISSUE THREAD

**Issue by dethell** [jasny/bootstrap#420]
I am using offcanvas with data- attributes, but I also need to interact with the menu in code, specifically, when showing a bootstrap modal from the menu I want the menu to close. Currently it stays open and the modal shows on top of the menu and only closes when the modal closes.

I tried adding this code to my document ready code:

```
$('.modal').on('shown.bs.modal', function () {
    $('.navmenu').offcanvas('hide');
});
```

When I do that I get an error that the off canvas function is undefined.

**Comment by jasny** [comment]
I can't reproduce that. Please create a JSFiddle demonstrating the issue.

**Comment by Minstel** [comment]
Closing, as there is no feedback.
