### ISSUE TITLE
[Rowlink] Open with ctrl-clic or mouse click

### ISSUE THREAD

**Issue by gdebrion** [jasny/bootstrap#422]
Hello,

It is not possible today to open a row link with a control-click or a mousewheel click. Is it possible to add it?

Thanks for your work!

**Comment by jasny** [comment]
@gdebrion It would be great if you could create a PR for this. Thanks!

**Comment by gdebrion** [comment]
If I could fix it myself, it will be already done. Unfortunately I don't really understand JS as you written it…

**Comment by jasny** [comment]
ok
