### ISSUE TITLE
Can't place a fixed positioned element inside navmenu.

### ISSUE THREAD

**Issue by AjayKanayil** [jasny/bootstrap#423]
![capture](https://cloud.githubusercontent.com/assets/7960725/11395091/f8aae928-938e-11e5-87a3-c58ee8d94f7a.PNG)
I am trying to place a fixed header for navmenu, but it gets pulled out off offcanvas while opening it.
Is there any solution??

**Comment by jasny** [comment]
Yes there is the (undocumented :frowning:) `exclude` option which can be used for this.

    $('.navmenu').offcanvas({'exclude': '.my-fixed-element'});
