### ISSUE TITLE
Hide off canvas

### ISSUE THREAD

**Issue by redayoub** [jasny/bootstrap#427]
Hello, thanks for this useful plugin.

I have four offcanvas in the same page and each one have it's own button that triggers it. Initialy canvas are hiden but if I show one of them and I click on the button that shows an other canvas I get two canvas shown at the same time. Is there any way to hide first others canvas if they are open before shownig an other one ?

Thanks.

**Comment by jasny** [comment]
Yes use something like

    $('menu1').on('show.bs.offcanvas', function() {
      $('menu2').canvas('hide');
      $('menu3').canvas('hide');
    ]);

If you need more help on this, please as a question on [StackOverflow](http://www.stackoverflow.com) where there is a whole community to help you out.
