### ISSUE TITLE
Jasny Bootstrap is looking for collaborators

### ISSUE THREAD

**Issue by jasny** [jasny/bootstrap#430]
Jasny/Bootstrap has proven to be very useful for a lot of people. Unfortunately the popularity means it costs a fair bit of time to maintain the quality of the project. More time than I (the main contributor @jasny) has at hand.

How it currently stands it that it desperately needs collaborators to thrive and survive.

If you're interested, please leave a comment and/or send an e-mail to arnold@jasny.net.

**Comment by jasny** [comment]
Especially those who have contributed in the past: @arekkas @cvrebert @flexponsive @mente @Dehalion @phaseOne @voidmain02 @pbatey @kkirsche @dvc94ch @Misiu @ipoval @brandoncc @hisie @jesperronn @samuelscheid @Kronuz @jodytate @eneveu @sergiors @mkoryak @mikezielonka @ShinyChang @BBosman @josh-bradley @asessa @daftspunk

**Comment by sergiors** [comment]
:+1:  what's the roadmap?

**Comment by jasny** [comment]
The plan is not set in stone, but I'm considering the following:

1. Break up Jasny Bootstrap into standalone plugins
2. The Jasny Bootstrap itself remains and combines all plugins into a single build
3. Collaborators can work on the plugin(s) they love, fixing issues and implementing features.
4. Travis will automatically build a new version when a plugin each time a plugin has a new release.

This makes the project more maintainable. I'd like collaborators to take (partial) responsibility of a plugin, though this is not a requirement. Ownership of a plugin might be changed if a developer is really putting a lot of love and care in it.

I've started marking issues as 'low' and 'high' prio. Some issues are affecting a large set of the users. They need to be addressed. Others can be picked up at will. The high prio issues to be solved before looking to adding more features.

When Bootstrap 4 hits Beta, we'll shift focus on version 4, which needs to be compatible. 

We might start a [Telegram](https://telegram.org/) group or just chat on [Gitter](https://gitter.im/jasny/bootstrap).

In the future we might incorporate other standalone Bootstrap plugins and so add collaborators and functionality.

**Comment by jasny** [comment]
@bloopletech It would be great it you could join as collaborator.
