### ISSUE TITLE
Slide In (offcanvas-sm) for all width

### ISSUE THREAD

**Issue by alphadc** [jasny/bootstrap#432]
Hello,

I found that your off canvas is amazing! 

I have one questions about the slide in effect for the menu. When I added "offcanvas-sm", it has "slide in" effect, but only for under 992px, how can I make it works for all screen resolution?

Thank you.

**Comment by jasny** [comment]
Isn't `offcanvas` (without `sm`) working for you?

**Comment by alphadc** [comment]
It's working, but it's pushed the main HTML. I need "Slide In" effect, but for all screen resolution.

**Comment by jasny** [comment]
The effect should be affected by the class. Can you make a jsfiddle showing it's not properly working for large screens? Thanks

**Comment by Minstel** [comment]
Closing, as there is no feedback, and menu seems to work correctly on large screens.
