### ISSUE TITLE
Push-Right menu?

### ISSUE THREAD

**Issue by cognopatrick** [jasny/bootstrap#437]
Hey,

I love your work, i'm looking for an option to use the pushmenu also on the right? I'v been tryin to figgure out how but it's a bit hard. Maybe you could help me a little?

**Comment by jasny** [comment]
Please read the docs:

http://www.jasny.net/bootstrap/components/#navmenu-fixed
http://www.jasny.net/bootstrap/javascript/#offcanvas-usage (`placement` option)
