### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by shoudaos** [jasny/bootstrap#438]
Bootstrap 4 support?

**Comment by jasny** [comment]
We'll start working on Bootstrap 4 support when twbs releases a beta version.

**Comment by Unichron** [comment]
beta is released now FYI

**Comment by simplyniceweb** [comment]
Beta is on.

**Comment by pivica** [comment]
If anybody is interested i've ported offcanvas.js and related _offcanvas.sccs and _navmenu.scss to Bootstrap 4 beta version 274f91de71d6951e1eff5e09b067223abe31e14e. Didn't tested all possible cases but should be working fine for basic offcanvas cases.

**Comment by raisonon** [comment]
Is Jasny compatible with BS4?

**Comment by seandelaney** [comment]
Any updates on BS4 ?

**Comment by jasny** [comment]
We're working on it.

**Comment by geekita** [comment]
> 
> 
> We're working on it.

Any insights about next release?

**Comment by Minstel** [comment]
Version, supporting BS4, is released: https://github.com/jasny/bootstrap/releases/tag/v4.0.0
