### ISSUE TITLE
travis-ci failed

### ISSUE THREAD

**Issue by brcontainer** [jasny/bootstrap#445]
@jasny  Travis-ci using several deprecated tools:

1. `--use-mirrors` is not avaliable in pip7.0.0 or high
2. Node.js 0.10 is deprecated
3. boto==2.20.0 is deprecated

**Comment by jasny** [comment]
* We don't need boto (or AWS). Lets remove it.
* Use node.js v4

**Comment by brcontainer** [comment]
@jasny it's sound great :D Thanks!!

**Comment by jasny** [comment]
Also let's remove the dependency of saucelabs and use [PhantomJS](http://phantomjs.org/) instead.

**Comment by jasny** [comment]
Fixed by #481
