### ISSUE TITLE
[Offcanvas menu] Javascript clone more div.offcanvas-clone

### ISSUE THREAD

**Issue by YokiToki** [jasny/bootstrap#451]
When call `$('.offcanvas').offcanvas('show');` then `$('.offcanvas').offcanvas('hide');` each time creates more and more `div.offcanvas-clone`

**Comment by MrUpsidown** [comment]
Same here. A fix to that would be nice. Tried the beta version and the same happens.

**Comment by jasny** [comment]
https://jsfiddle.net/hrcxt5qj/

**Comment by IgnacioGans** [comment]
hi, Jasny. 

if i wanna a second button in navbar on the same page, i should add the second button but change the name of data-target='navmenu2', right?.
