### ISSUE TITLE
webpack issue

### ISSUE THREAD

**Issue by geohuz** [jasny/bootstrap#455]
I'm trying to use with webpack, the npm install works fine, but got errors when running webpack:

```
Module not found: Error: Cannot resolve module 'jasny-bootstrap' in ....
```

I have 
```
import 'jasny-bootstrap'
```
in my main.js file

**Comment by NicholasGWK** [comment]
I believe this is caused by the "main" entry in package.json of jasny bootstrap. It says dist/jasny-bootstrap.js whereas it should be dist/js/jasny-bootstrap. Change that and it works...not sure if this is intended but I'll submit a PR.

**Comment by ibiza240** [comment]
Hi, I got this exact problem, with jasny-bootstrap version 3.1.3.

In its package.json, I see for the "main" entry: "js/jasny-bootstrap", should that be correct now?

I tried to change it to "dist/js/jasny-bootstrap" but I still am unable to use hsny-bootstrap with webpack, I get the Module not found error :(

**Comment by NicholasGWK** [comment]
Hey @ibiza240 , how are you installing Jasny bootstrap? The fix isn't in 3.1.3 so you might be better off npm installing from the master branch. If you need to use 3.1.3, make sure you're putting the main: 'dist/js/jasny-bootstrap' in the root of the package.json and not just updating the main entry under jspm :)

**Comment by ibiza240** [comment]
Thanks for the swift update! I am installing with `npm -install jasny-bootstrap` and it downloads the version 3.1.3. 

Would you advise to use the master branch or fix locally and continue with 3.1.3?

**Comment by ibiza240** [comment]
Also, can you explain a bit more what you mean by "main: 'dist/js/jasny-bootstrap' in the root of the package.json and not just updating the main entry under jspm :)" please? I can't quite get it (still new to node, npm and all that :S)

Thanks!

**Comment by nejtr0n** [comment]
Same issue. I have installed package from master branch. But webpack could not find module.

**Comment by barnabaskecskes** [comment]
Having the same issue - latest release is 3.1.3. installing through npm. For now, I did replace `require('jasny-bootstrap');` with `require('jasny-bootstrap/dist/js/jasny-bootstrap');` in my javascript and that seems to have fixed the error.

**Comment by jonasva** [comment]
same issue here
