### ISSUE TITLE
disable background elements when offcanvas is activated

### ISSUE THREAD

**Issue by tijiro** [jasny/bootstrap#458]
First of all, thanks to great ideas.

I'm using Jasny Offcanvas navigation for my mobile website.
In my mobile page there are so many "a" elements.

The problem is when offcanvas activated in mobile.
somebody click outside of offcanvas menu to close the offcanvas. (as they expected)
But it causes click the links of the background's elements.

Is there any good idea to make background disabled when offcanvas is activated?

**Comment by robleeper** [comment]
It's a CSS fix instead of a programmatic fix, but...

You could create an empty div with an absolute position, 100% width, 100% height. Then, when the body gets its class of .canvas-slid, change the divs z-index so it blocks everything.
