### ISSUE TITLE
Please make jasny npm ready.

### ISSUE THREAD

**Issue by notsure** [jasny/bootstrap#459]
It would be nice if you could register npm at https://www.npmjs.com/ so we could download it via npm.

**Comment by kosiakMD** [comment]
It's Bower ready, 1st install 
$ npm install bower
Than instal Jasny
$ bower install jasny-bootstrap

**Comment by notsure** [comment]
Yes I know, however sometimes it is quite nice to have all out of one hand.

Currently I download each dependency via npm.

**Comment by chrisber** [comment]
Would be nice if it could play with webpack out of the box :smile: 
@notsure  How do you manage each dependency via npm?

**Comment by notsure** [comment]
@chrisber to be honest I'm not fully happy with the npm solution yet. However if you are using browserify it is quite good. Also for small projects it makes sense as you only have e.g. gulp and npm as development requirements. 

I define all dependencies in my `package.json` under `dependencies`, like you would in your `bower.json`.

```
{
    "name": "foo",
    "dependencies": {
        "bootstrap": "3.3.6",
        "jquery": "2.1.4",
        "moment": "2.13.0"
    }
}
```

Running `npm install` downloads all your defined dependencies into the `node_module` folder. A gulp task compiles all dependencies to a single vendor.js / vendor.css file and thats it.

**Comment by medhatdawoud** [comment]
It's a good and important step to have this lib on NPM, because me too use npm to load all my dependencies

**Comment by Bennethon** [comment]
I would also like this. Currently I install jasny-bootstrap with npm by pointing my package.json at the github repo, but it is not ideal. I would rather use npm's rigistry.

```
  "dependencies": {
    "bootstrap-sass": "3.3.7",
    "jasny-bootstrap": "git://github.com/jasny/bootstrap.git#97e2d4ad4860f8628105f5d3f4cfb695aab881e0",
    "jquery": "2.2.4"
  },
```

**Comment by poratuk** [comment]
Done in the #536.
