### ISSUE TITLE
Can i have two button for each off-canvas?

### ISSUE THREAD

**Issue by IgnacioGans** [jasny/bootstrap#461]
Hi, Jasny.
I'm trying to make off-canvas Left and Right on the same Page Web and
I make my own off-canvas, but i'm not sure if i did well ... is look like something different.
I should use data-placement="left or right" to do off-canvas Left and Right...? 
Anyway i drop my sample... if you can check that and give some answer about that, I'd appreciate it.

P.D: This project is Awesome, Keep Going! XD

**Comment by muhammad-ihsan** [comment]
yeah you can have 2 off-canvas both of them. simply, u need to have 2 of navmenu-canvas and 2 of trigger button for it.
