### ISSUE TITLE
[Reopened] Offcanvas closing when interacting with dropdown

### ISSUE THREAD

**Issue by MikiSoft** [jasny/bootstrap#462]
Related to [this](https://github.com/jasny/bootstrap/issues/457) issue. @jasny, I've tested it like you said with the newest (beta) version and it still doesn't work, so please consider fixing this really serious bug for Firefox (on PC) and other various mobile browsers.
**Update:** It seems that it's related to Bootstrap JS, anyone can confirm?

**Comment by kosiakMD** [comment]
.dropdown-backdrop
div-class created by clear Boostrap
decisions:
1) change z-index
2) delete element each time

**Comment by Minstel** [comment]
@MikiSoft @clongboat  @kosiakMD 
Well, the reason for this seems pretty simple. If we take a look at bootstrap code, that handles opening dropdown, we'll find the following:

```
Dropdown.prototype.toggle = function (e) {
  ...
  if ('ontouchstart' in document.documentElement && !$parent.closest('.navbar-nav').length) {
    ...
    ... .addClass('dropdown-backdrop')
    ...
  }
}
```

So we can see, that backdrop is added when:
- device is touchable
- and dropdown does not have `.navbar-nav` among it's parent. Like if it is intended to be used only in that way.

First condition can become `true` on touchables and, unfortunately, in FF on desctop. See this issue: https://github.com/twbs/bootstrap/issues/13748. Also it points to coresponding FF bug. According to this, users, that do not use dev tools, will never face that behaviour. That's good:)
Bad is that it happens on touchables. I tested it on Google Nexus, in Chrome - backdrop is there, causing offcanvas to close.

The way to solve this seems the following: 
- to add `navbar-nav` class to one of dropdown parents (for ex., to offcanvas menu). And if we do not need it's style effects, then compensate them with other styles. That, of course, seems not entirely correct. But it can solve the problem. That's like a workaround
- or to delete backdrop after each dropdown opening. I'll create a PR with this happening in jasny/bootstrap

**Comment by askdesign** [comment]
I modified the JS with @jasny's most recent beta version, but the problem persisted.
https://github.com/jasny/bootstrap/commit/04ab9af0fbecafb2708e32a137f5446893b82ce2

So, thank goodness I found this thread!

I added the navbar-nav class to the parent div (offcanvas menu) and everything now works! Thank you for your solutions!
