### ISSUE TITLE
Don't close the offcavas on any click

### ISSUE THREAD

**Issue by katindo** [jasny/bootstrap#464]
Hi,
Thank you for sharing!

I was wondering if there's a way to make the offcanvas menu close only when someone clicks on a "close" button.

Right now, the menu closes every time someone clicks anywhere in the page.

**Comment by uiprototype** [comment]
I have the same problem too. Hope there is a solution...

**Comment by jasny** [comment]
You can set `autohide` to false. http://www.jasny.net/bootstrap/javascript/#offcanvas

For a close button you nee to use JavaScript.

```
$(document).on('click', '.close-offcanvas', function() {
   $('.offcanvas').offcanvas('hide');
});
```
