### ISSUE TITLE
[OffCanvas Menu] scrolling with body on small screen.

### ISSUE THREAD

**Issue by Luizgpp** [jasny/bootstrap#467]
![offcanvas](https://cloud.githubusercontent.com/assets/14079349/16995284/de3bb5e6-4e81-11e6-88bc-dda0426dbc8d.gif)
![off canvas push menu bug](https://cloud.githubusercontent.com/assets/14079349/16967585/ff153596-4ddf-11e6-9ea4-fb58b5f02bc6.png)
![off canvas push menu bug 2](https://cloud.githubusercontent.com/assets/14079349/16967589/03082fd2-4de0-11e6-8b14-50ff69e885bc.png)

The first image is without scroll, the second image is with scroll.

The menu scroll together body content.

I tested on firefox and Chrome, just on Chrome the bugs appear.

**Comment by Luizgpp** [comment]
Any idea to solve this? I can't find error on chrome.

**Comment by dossan** [comment]
@Luizgpp You may need to include the relevant code...

**Comment by Luizgpp** [comment]
@dossan here http://www.jasny.net/bootstrap/examples/navmenu-reveal/
Just use developer tool on chorme, change to mobile view and the bug appear.
Thanks!

**Comment by dossan** [comment]
@Luizgpp What do you mean that the first image is without scroll? Anyway, so far I've not been able to reproduce what you're situation...

**Comment by Luizgpp** [comment]
@dossan In gif you can see, open the offCanvas and scroll, menu and body scroll together.

**Comment by dossan** [comment]
@Luizgpp Yes, they scroll together also for me, but I don't think that's a bug, but just the way it was implemented. @jasny should provide us with more info.

**Comment by Luizgpp** [comment]
@dossan I thinks this is all about incompatibility on Chrome.

**Comment by srijaydeathwish** [comment]
The javascript adds '.canvas-slid' to the body when offcanvas is toggled but 'canvas-slid' makes body position: relative.  forcing it to 'fix' seems to stop body scrolling. but page jumps to top if you have scrolled to bottom.

```
body.canvas-slid {
    position: fixed !important;
}
```

**Comment by Minstel** [comment]
@dossan I do not see it scrolling anymore. Tested in Chrome 55.0.2883.87 m

**Comment by poratuk** [comment]
This issue still exists. Its only works on the mobile devices (tested on mobile Chrome Andoid + Windows Chrome on device inspection).
I do not know how solution can be done to fix this problem:
This is on the OffCanvas.prototype.slide function. 
https://github.com/poratuk/bootstrap/blob/master/js/offcanvas.js#L144
Here are changes left and right css properties for body. But when Body setted left: 300px, right steal left 0. Inside divisions are increase height. But navmenu also increase his height.  When body right setted -300px. Inside divisions return his height. But navmenu are left this increased height. 

I try many solutions, but any do not help.

**Comment by Minstel** [comment]
I do not see this happening anymore in the latest version of Chrome (67). So either this was fixed in a browser, or we fixed it unintentionaly here. So closing the issue.
