### ISSUE TITLE
File input - Cancel file change deletes file name on Chrome

### ISSUE THREAD

**Issue by iaguilera** [jasny/bootstrap#470]
In file input, when pressing change button to change the file, file dialog is shown. If instead of selecting a new file we cancel the dialog, the previous file name is deleted.

This only happend me in Chrome (52.0.2743.116 m), Firefox and IE works ok.

**Comment by jasny** [comment]
@iaguilera Can you please compare this to the default behavior of `<input type="file">` in Chrome vs Firefox.

The file input element provides a nice user interface, but doesn't alter the behavior of the browser's file input element.

If you're still sure it's a bug, please provide a [jsfiddle](http://jsfiddle.net) demonstrating the issue.

**Comment by jeroenhoekstra** [comment]
I'm experiencing the same issue in Chrome (Version 54.0.2840.71 m (64-bit)). Firefox works as expected (preview stays visible). In my case the preview image disappeared after clicking the cancel button in the dialog. You can try it yourself on the demo page: http://www.jasny.net/bootstrap/javascript/#fileinput

**Comment by Minstel** [comment]
@iaguilera @jeroenhoekstra 
That's a Chrome issue. It behaves the same with standart file input.

**Comment by warmachine7733** [comment]
Here is a work around for that in js 

<!DOCTYPE html>
<html>

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        .file {
            position: fixed;
            left: 100px;
            top: 10px;
        }

        .button {
            position: fixed;
            left: 400px;
            top: 10px;
        }
    </style>

</head>

<body>
    <input type="file" class="file" onchange="changeFile(event)" onclick="clickFile(event)" id="file" />
    <div id="log" style="display:none"></div>
    <ul id="ul">
    </ul>
    <br/>
    <br/>
    <input type="button" class="button" onclick="removeFile()" value="remove" />

    <script>
        var clone = {}
        function changeFile(event) {

            var fileElement = event.target;
            if (fileElement.value == "") {
                var file = document.getElementById("file")
                document.body.appendChild(clone[fileElement.id]); //adding clone 
                file.parentNode.removeChild(file); //removing parent 
            }
        }

        function clickFile(event) {
            console.log("click event is fired")
            var fileElement = event.target;
            if (fileElement.value != "") {
                clone[fileElement.id] = fileElement.cloneNode(true); //cpoying clone
            }

        }

        function removeFile() {
            document.getElementById("file").value = "";
        }
    </script>

</html>

**Comment by warmachine7733** [comment]
here is a work around in js :
https://jsfiddle.netmgpwr1as
