### ISSUE TITLE
Variable name issues when running with Bootstrap 4.0.0-alpha.3

### ISSUE THREAD

**Issue by AnneAtLukkien** [jasny/bootstrap#471]
When trying to run Jasny-Bootstrap with Bootstrap 4.0.0.-alpha.3 I get various error messages with the names for variables, for instance:

NameError: variable @container-lg is undefined 

This is the first variable that gets the error, but when I 'fixed' this one, there were more variables that are not known within Bootstrap 4.0.0.-alpha.3.

Any idea how I can run Jasny-Bootstrap 3.1.3 (or another version) successfully with Bootstrap 4.0.0.-alpha.3 ?

**Comment by Minstel** [comment]
@AnneAtLukkien Bootstrap 4 dropped lots of LESS variables. But they are still actively in use in jasny/bootstrap, so I think it can not be used with Bootstrap 4 for now.

There is already an issue for this created: https://github.com/jasny/bootstrap/issues/438
