### ISSUE TITLE
Travis should build the project

### ISSUE THREAD

**Issue by jasny** [jasny/bootstrap#476]
We should remove the 'dist' folder from the development branches (master). After the tests are run:
- [A new release should be created on GitHub](https://docs.travis-ci.com/user/deployment/releases) (will create a tag)
- [A new version should be released to npm](https://docs.travis-ci.com/user/deployment/npm)

See also #445

**Comment by poratuk** [comment]
Are dist folder must be removed from grunt tasks ? Can this will be described more.
