### ISSUE TITLE
Something in the Oct 3 commits broke our offcanvas menus.

### ISSUE THREAD

**Issue by Bennethon** [jasny/bootstrap#485]
The link to reveal offcanvas menus no longer works after getting the Oct 3 updates.

```
<a href="#" onClick="return false;" data-toggle="offcanvas" data-target="#sidePanel">Menu Link</a>

<nav id="sidePanel" class="navmenu navmenu-default navmenu-fixed-right offcanvas-sm">
...
</nav>
```

I have reverted to the commit before Oct 3 (SHA 97e2d4ad4860f8628105f5d3f4cfb695aab881e0) and it works fine.

**Comment by Minstel** [comment]
@Bennethon It works ok with current version.

**Comment by Minstel** [comment]
Closing, as now there is no problem with reveal menu.
