### ISSUE TITLE
Sass files are missing things

### ISSUE THREAD

**Issue by centurianii** [jasny/bootstrap#492]
Take this variable: `$line-height-computed`
in sass files there is no initialization but in less files there is in one place (dir less/build): 
`@line-height-computed:    floor((@font-size-base * @line-height-base)); // ~20px`
but not in another (dir less).
It's a node as I figured project-I'm not using it neither I will-I'm astonished with the messy code: duplicate files for starters, configurations on top of configurations etc.!
The people behind Node should be responsible to handle **importing simple projects from github to Node and NOT vice-versa**!
Why should we use such lengthy sass/less files for everything? What about re-using bootstrap variables?
From BEM perspective it is a no-go.

**Comment by poratuk** [comment]
https://github.com/jasny/bootstrap/pull/518
