### ISSUE TITLE
modal bootstrap confict (Solved)

### ISSUE THREAD

**Issue by umerthow** [jasny/bootstrap#496]
when i embedded fileinput.js it has conflict with bootstrap.min.js.
 because when i showing modal it will dismiss quickly, , can i fix it??

thanks

**(Solved)**

**Comment by jasny** [comment]
There shouldn't be a conflict. Please create a [jsfiddle](http://jsfiddle.net) to demonstrate the issue.

**Comment by umerthow** [comment]
has solved jasny, this issue caused  double link of bootstrap.min.js on my page,

thank you.
