### ISSUE TITLE
Fileinput problem for edit image operation

### ISSUE THREAD

**Issue by flizana** [jasny/bootstrap#504]
I am currently using fileinput for image upload without any problem at all. Although it works for a new image upload, I am having an issue when trying to edit this image.

My code for new image upload is the following:

    <div class="fileinput fileinput-new" data-provides="fileinput">
        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
            <img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxOTAiIGhlaWdodD0iMTQwIj48cmVjdCB3aWR0aD0iMTkwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9Ijk1IiB5PSI3MCIgc3R5bGU9ImZpbGw6I2FhYTtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxMnB4O2ZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5zLXNlcmlmO2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjE5MHgxNDA8L3RleHQ+PC9zdmc+" alt="...">
        </div>
        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
        <div>
            <span class="btn btn-default btn-file">
                <span class="fileinput-new">Seleccionar Archivo</span><span class="fileinput-exists">Cambiar</span><input id="input-image-file" type="file" name="productImageFile" required>
            </span>
            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
        </div>
    </div>

As you can see I am using the `required` attribute in the `input` tag to ensure an image file is uploaded (this is a requirement). For the edit operation I changed the `class` of the first `div` tag from `fileinput-new` to `fileinput-exists`. The image shows up along with the appropriate buttons, but if I try to submit the form, the browser won't let me submit it because "There is no file selected" message shows up. How can I "fool" the browser into thinking there is a file already selected?

Thanks!

**Comment by poratuk** [comment]
I test it on my local browser, then test on the jsfiddle. 
All wokrs fine in me. 
https://jsfiddle.net/poratuk/d063robh/1/

Can you give example where you are do not have worked fileinput ?

**Comment by flizana** [comment]
I already solved the problem! I did a workaround. Thanks anyway.

**Comment by wslpeter** [comment]
how did you solve the problem,I have the same problem,thank you

**Comment by poratuk** [comment]
@flizana Hey. How you are solve it ?

**Comment by wslpeter** [comment]
@flizana thank you!
