### ISSUE TITLE
<body>'s "overflow" should be set to "auto" in offcanvas & jasny-bootstrap.min.js ？

### ISSUE THREAD

**Issue by jzoe** [jasny/bootstrap#522]
I'm using the jasny-bootstrap to create my sidebar navmenu, but I find out the <body> element's overflow attribute have been set to "hidden" which confuse me a lot. It makes the body element cann't be scoll even through  I  setting this attribute on body.

**Comment by jzoe** [comment]
Any way thanks for you work! If any one have the same problem with me, you can try to change the body.overflow's value form "hidden" to "auto" in offcanvas.js & jasny-bootstrap.min.js

**Comment by poratuk** [comment]
This is not a issue. 
To body attribute `overflow:hidden` are setted to prevent scroll on body. This style must be removed when you are close the navmenu.
If you are wont scroll body, you need add to navbar: `data-disableScrolling="false"`.
[http://www.jasny.net/bootstrap/javascript/#offcanvas-usage](Settings)
