### ISSUE TITLE
Photo cleaning -  widget for uploading photos

### ISSUE THREAD

**Issue by RogerMito** [jasny/bootstrap#531]
817/5000
Hello my friend!

I'm talking here about Brazil; First of all, congratulations for the work. The Jasny Bootstrap components are being of great help.

More specifically, I'm using the widget for uploading photos. I'm like a doubt and I hope you can help me.

How do I make the contents of the widget clean without requiring the "Remove" button to be used?

I want the action of the "Remove" button to fire in my view, but in another element.

Angular Usage JS, I would like to do the following: "<button ng-click =" clearPhoto "> clearPhoto </ button>"

For this I must be able to create a function of the type in my controller:
$ Scope.clearPhoto ()
{
         // Action to clean the widget.
         // Same principle of the "Remove" button present in the body of the widget you made.
}

Thank you very much.

**Comment by jasny** [comment]
For questions please use [StackOverflow](http://www.stackoverflow.com). Thanks
