### ISSUE TITLE
Webpack 2: Module not found: Error: Can't resolve 'jasny-bootsrap'

### ISSUE THREAD

**Issue by dratkovic** [jasny/bootstrap#545]
Hi,
After npm install I was getting this error all the time. Fix was to add   "main": "./dist/js/jasny-bootstrap.js",
in paskage.json. Can you please also add it so that after npm install there is no need to update.

Thanks,
Damir

**Comment by jasny** [comment]
@dratkovic A PR is appriciated

**Comment by vicentenoriega** [comment]
Pull request:

https://github.com/jasny/bootstrap/pull/549

Regards :)

**Comment by GoPro16** [comment]
Please update npm to reflect the latest update. Just checked the package.json and its still has the previous change in there.
