### ISSUE TITLE
Content div problem

### ISSUE THREAD

**Issue by spider58** [jasny/bootstrap#546]
Hello. My english is bad sorry for that.

Can we resize (decrease width) content div instead of moving to right size when open the navbar?

Because my content div has another div inside which fixed right. And its disappear when open the navbar.

Adding scrollbar is not solving my problem. I dont want to add scrollbar.

Thanks inadvance.

**Comment by jasny** [comment]
1. With which component are you experiencing this issue.
2. Can you please include a [jsfiddle](https://jsfiddle.net/) (read the [tutorial](http://doc.jsfiddle.net/tutorial.html))

**Comment by spider58** [comment]
Ok. Sorry for my bad.

https://jsfiddle.net/k9K5d/267/

as you can see right div is disappearing after navbar opened.

**Comment by poratuk** [comment]
@spider58 Unforently on offcanvas menu whole body element are moving right. 
You can use trigers: `show.bs.offcanvas`, `hide.bs.offcanvas` move yours block also on . 
You can see demo on https://jsfiddle.net/k9K5d/269/

```$('.navmenu').on('shown.bs.offcanvas', function() {
	$('#mydiv').css('right', parseInt($('#mydiv').css('right')) + parseInt($(this).css('width')));
});

$('.navmenu').on('hide.bs.offcanvas', function() {
	$('#mydiv').css('right', parseInt($('#mydiv').css('right')) - parseInt($(this).css('width')));
});```

**Comment by jasny** [comment]
@spider58 Having the whole body slide out is one of the effect you can pick.It acts like that because the `canvas` is set to `body`. If you don't set the `canvas` only the menu slides.

https://jsfiddle.net/zjkq1xm4/

**Comment by spider58** [comment]
Thanks for all replies.
