### ISSUE TITLE
In file input, when pressing change button to change the file, file dialog is shown. If instead of selecting a new file we cancel the dialog, the previous file name is deleted.  This only happend me in Chrome, Firefox and IE works ok.

### ISSUE THREAD

**Issue by Ducky260289** [jasny/bootstrap#550]
In file input, when pressing change button to change the file, file dialog is shown. If instead of selecting a new file we cancel the dialog, the previous file name is deleted.

This only happend me in Chrome, Firefox and IE works ok.

**Comment by Ducky260289** [comment]
help me!

**Comment by Minstel** [comment]
@Ducky260289 Unfortunately. that's a default behaviour of fileinput in Chrome.
