### ISSUE TITLE
I doesnt work in IE when 2 control used

### ISSUE THREAD

**Issue by tieudoan208** [jasny/bootstrap#566]
when i used 2 control textbox  datetime, i ented valide value first control, when i tab or focus second then it not enter value.

**Comment by tieudoan208** [comment]
Here code it run repeat 

`Inputmask.prototype.focusEvent = function () {
        this.focusText = this.$element.val()
        var len = this.mask.length
        var pos = this.checkVal()
        this.writeBuffer()

        var that = this
        var moveCaret = function () {
            if (pos == len)
                that.caret(0, pos)
            else
                that.caret(pos)
        }

        moveCaret()
        setTimeout(moveCaret, 50)
    }

    Inputmask.prototype.blurEvent = function () {
        this.checkVal()
        if (this.$element.val() !== this.focusText && this.$element.val()!="") {
            this.$element.trigger('change')
            this.$element.trigger('input')
        }
    }`

**Comment by jasny** [comment]
IE support is dropped
