### ISSUE TITLE
File Input Dynamically Add File to File Input

### ISSUE THREAD

**Issue by Peace-N** [jasny/bootstrap#572]
I have been having a challenge with file input, i need to dynamically add file data to this widget, I have the data coming from the DB, so sort of preselected file ..

Help will be appreciated ..

**Comment by Minstel** [comment]
@Peace-N Hi! Sorry for not answering for so long, we didn't have time to review issues. Is your question still actual?

If so, do you mean it's preselected on page load, or after page load (like file is selected from DB, say, via AJAX)?

**Comment by jasny** [comment]
This is possible with the `.fileinput-new` and `.fileinput-exists` classes.
