### ISSUE TITLE
the right of the navmenu (the contianer) is not in the right place

### ISSUE THREAD

**Issue by vipkouyu** [jasny/bootstrap#573]
![20180126165404](https://user-images.githubusercontent.com/29297132/35432024-bb606e20-02b9-11e8-8fe9-3557e255fc9c.jpg)

the div container does not in the right place, how to fix it?

**Comment by Minstel** [comment]
@vipkouyu Can you provide your code, that you use for this page?

**Comment by jasny** [comment]
Closing; no response from @vipkouyu.
