### ISSUE TITLE
Offcanvas menu - canvas-slid class problem

### ISSUE THREAD

**Issue by TomThak** [jasny/bootstrap#575]
Hello,
your offcanvas menu adds .canvas-slid after animation has ended.
It means, when you have differently styled content of menu for mobile and desktop
and you want to style it differently, when it is opened as offcanvas, all styles are applied 
after the animation has ended and styling blinks.

Is it possible to for example:
add this class before animation has ended or to add FadeIn effect for the content inside offcanvas?

**Comment by Minstel** [comment]
@TomThak When menu is in process of sliding, it has a class `canvas-sliding`. So you should just add your custom styles also for this class, as well as for `canvas-slid`.
