### ISSUE TITLE
Publish new stable release

### ISSUE THREAD

**Issue by pedrofurtado** [jasny/bootstrap#578]
Is this library still maintained? Because the last stable release version was published in 2014.

**Comment by aadrian** [comment]
@pedrofurtado unfortunately it seems to be abandonware :( .

**Comment by Minstel** [comment]
@pedrofurtado @aadrian Well, it's not abandoned) We just do not have spare time now. Currently we're on payed projects and on other opensource, like `jasny mongo-db`. As soon as other priorities are done, or some time appears, we are go back to this one.

**Comment by aadrian** [comment]
@Minstel than at least could you please merge or reject the PRs?

**Comment by Minstel** [comment]
@aadrian I'll ask the main mantainer to merge, when he has time.

Unfortunately, I can not merge by myself.

**Comment by jasny** [comment]
We've set the bar too high for a new release (see project) considering the time that we have.
I'll merge the PRs and add a release.

Some lesser used components will be dropped in order to keep this maintanable.

Last, we could really use some extra help on this project.

**Comment by swiffer** [comment]
@jasny, new Version is Out now, Right? Can you publish to npm also?

**Comment by Minstel** [comment]
@swiffer Publishing was broken some time ago. It should be fixed in closest time.

**Comment by Minstel** [comment]
@swiffer Publishing is fixed. Next major release, that supports BS4, is released.

**Comment by swiffer** [comment]
Thanks! Does it still work with bootstrap 3 (and If Not, can you publish 3.2.0) as well?
