### ISSUE TITLE
Bootstrap 4.1.3 modal in Firefox conflict

### ISSUE THREAD

**Issue by TomThak** [jasny/bootstrap#595]
Hello,
when I include jasny bootstrap the latest version into my page with the latest release of bootstrap,
there is a bug, that modals stop working in firefox. If i check the code, it simply does not handle css properties like display: block and adding class to dialog html. It works in Chrome and IE, but in the latest FireFox it does not work and dialog modal does not show.

**Comment by Minstel** [comment]
@TomThak Current latest release of Jasny Boostrap (3.2.0) does not really support BS4. We'll add this support in next major release.
