### ISSUE TITLE
Image orientation using exif not working

### ISSUE THREAD

**Issue by rudresh-csp** [jasny/bootstrap#609]
### Type: Support/Bug

There is an issue with a project where I'm using the latest version of this. Few images especially clicked from using phones in `portrait orientation` get rotated.

I went to the issue and found the following condition in `fileinput.js`
```js    
preview.html($img)
if (Fileinput.options.exif) {
    //Fix image tranformation if this is possible
    Fileinput.setImageTransform($img, file);
 }
```

In the console(if i do `console.log(Fileinput.options)`), I'm getting this for every image.
![image](https://user-images.githubusercontent.com/30292416/70798604-63516000-1dcd-11ea-803a-a8fee62b3eef.png)

I have a few doubts, 
1. If I comment the if condition, it works fine. Just wanted to know the significance of this check, do we really need it?
2. Does it transform(rotates) the original file input as well? When I store the image and then came back to edit, it shows the original(untransformed one).

Thanks

**Comment by jasny** [comment]
Yes, use the `exif` option. I've added it the documentation.
