### ISSUE TITLE
website not opening 

### ISSUE THREAD

**Issue by harshitsinghwap** [jasny/bootstrap#613]
i wanted to see some examples or wanted to read official documentation but it seems, something wrong with hosting or domain name has been expired, please fix this asap

**Comment by babobski** [comment]
@jasny please fix this....where fishing in the dark now.

**Comment by jasny** [comment]
Thanks for reporting it. Checking out what's the problem.

**Comment by jasny** [comment]
For now, please visit https://jasny.github.io/bootstrap/

**Comment by babobski** [comment]
Thanks! that will do for now
