### ISSUE TITLE
Multiple file selection with custom file uploader

### ISSUE THREAD

**Issue by boonelab** [jasny/bootstrap#9]
When multiple files are selected in the custom file chooser, only the first file is displayed as opposed to having all files comma separated in the native file chooser

**Comment by julianxhokaxhiu** [comment]
Thank you @ducman version 2 was exactly what I was searching for, and you gave me a great inspiration! :D

**Comment by jasny** [comment]
@ducman Can you create a PR for this?

**Comment by dylanvdmerwe** [comment]
I still think multiple file uploads should be supported.

**Comment by Jany-M** [comment]
I would like to know if there's any plan to add all uploaded images previews (instead of just the first one)?
I posted [here too](https://github.com/jasny/bootstrap/issues/349).

**Comment by Minstel** [comment]
@Jany-M Hi! Yes, sure, we're currently thinking of the best way to do this. Implementing multiple uload without previews was just the first step.

**Comment by Jany-M** [comment]
Maybe generate a progressive ID for each preview "block", so that each has their own wrapped & targeted edit/remove buttons, then submit as array?

**Comment by ducman** [comment]
I don't want to drive people away from this great plugin but here is another bootstrap one dealing with uploading/preview, etc. I haven't tried it yet. Sharing is caring!! Good luck.

[http://plugins.krajee.com/file-input/demo](http://plugins.krajee.com/file-input/demo)

**Comment by Minstel** [comment]
@ducman Yeh, thanks, it looks really good :) Currently we try to think of smth more compact, not showing preview of each image separately.

**Comment by dylanvdmerwe** [comment]
Has this been resolved? Why is it closed?
